### ISSUE TITLE
cannot start service: fork/exec /bin/go-runner: no such file or directory

### ISSUE THREAD

**Issue by sed-i** [jnsgruk/zinc-k8s-operator#207]
Noticed a recurring error from zinc, during cos-lite itests as part of https://github.com/canonical/cos-lite-bundle/pull/80.

```
unit-zinc-0: 13:10:53 ERROR juju.worker.uniter.operation hook "zinc-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-zinc-0: 13:10:53 ERROR juju.worker.uniter pebble poll failed for container "zinc": failed to send pebble-ready event: hook failed
unit-zinc-0: 13:10:58 ERROR unit.zinc/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 106, in <module>
    ops.main(ZincCharm)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/main.py", line 456, in __call__
    return main(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 66, in _on_zinc_pebble_ready
    self._container.replan()
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/model.py", line 1984, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/pebble.py", line 1686, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-zinc-0/charm/venv/ops/pebble.py", line 1767, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "zinc" (cannot start service: fork/exec /bin/go-runner: no such file or directory)
----- Logs from task 0 -----
2023-09-29T17:10:58Z ERROR cannot start service: fork/exec /bin/go-runner: no such file or directory
-----
```

**Comment by jnsgruk** [comment]
Hmm, my suspicion is that this is this bug: https://github.com/juju/python-libjuju/issues/925

Are you able to get some more details? Like the version of Zinc reported or any debug output?

**Comment by sed-i** [comment]
Sounds right. The model is gone now, will update if I encounter again.
Thanks!
